#!/bin/sh

USERCOMMAND="$1"

SYNCCOMMAND="rsync -ru"

BITDIR=".bit"
BITSTORAGE="$BITDIR/files/"
BAREBITDIR="bit"
CONFIGFILE="$BITDIR/config"
[ -f $CONFIGFILE ] && . "$CONFIGFILE"

init() {
	if [ -z "$1" ]; then
		mkdir -p "$BITDIR" "$BITSTORAGE"
		echo "$BITDIR/" >> .gitignore
	else if [ "$1" = "--bare" ]; then
		mkdir "bit"
		echo "Empty bit repository initialized."
	else
		echo "Command $1 not recognised."
	fi
	fi
}

add() {
	FILE="$1"
	if [ -z "$FILE" ]; then
		echo "No file provided"
	else if [ -f "$FILE" ]; then
		echo "Adding $FILE"
		mv "$FILE" "$BITSTORAGE/$FILE"
		ln -s "$BITSTORAGE/$FILE" "$FILE"
	else
		echo "File not found"
	fi
	fi

}

bitrm() {
	FILE="$1"
	if [ -z "$FILE" ]; then
		echo "No file provided"
	else if [ -f "$FILE" ]; then
		if [ -f "$BITSTORAGE/$FILE" ]; then
			echo "Removing $FILE"
			rm "$FILE" "$BITSTORAGE/$FILE"
		else
			echo "$FILE not found in $BITSTORAGE"
		fi
	else
		echo "File not found"
	fi
	fi
}

clean() {
	NORMALFILES="$(find . -mindepth 1 | cut -d "/" -f2- | grep -v "^.git\|^.bit")"
	BITFILES="$(find .bit/ -mindepth 2 | cut -d "/" -f3-)"
	ERRANT=""
	bitLoopPipe=$(mktemp -u)
	mkfifo "$bitLoopPipe"
	echo "$BITFILES" > "$bitLoopPipe" &
	while read file; do
	exists=""
		normalLoopPipe=$(mktemp -u)
		mkfifo "$normalLoopPipe"
		echo "$NORMALFILES" > "$normalLoopPipe" &
		while read nfile; do
			[ "$nfile" = "$file" ] && exists="true"
		done < "$normalLoopPipe"
	[ -z "$exists" ] && ERRANT="$ERRANT$file\n"
	done < "$bitLoopPipe"
	if [ -n "$ERRANT" ]; then
		echo "Unreferenced files found:"
		printf "$ERRANT"
		read -p "Delete? Y/n: " response
		if [ "$response" = "" ] || [ "$response" = "y" ] || [ "$response" = "yes" ]; then
			printf "$ERRANT" | while read file; do
				echo "Removing $file"
				rm "$BITSTORAGE/$file"
			done
		fi
	else
		echo "No unreferenced files found."
	fi
}

pull() {
	echo "Syncing bit storage..."
	[ -z "$GITREMOTEORIGIN"] && git ls-remote && GITREMOTEORIGIN="$(git remote -v | grep "^origin.*(fetch)" | cut -d "$(printf "\t")" -f2 | rev | cut -d " " -f2- | rev)" || echo "Remote not found"
	$SYNCCOMMAND "$GITREMOTEORIGIN.git/$BAREBITDIR/" "$BITSTORAGE"
}

push() {
	echo "Pushing bit storage..."
	[ -z "$GITREMOTEORIGIN"] && git ls-remote && GITREMOTEORIGIN="$(git remote -v | grep "^origin.*(fetch)" | cut -d "$(printf "\t")" -f2 | rev | cut -d " " -f2- | rev)" || echo "Remote not found"
	$SYNCCOMMAND "$BITSTORAGE" "$GITREMOTEORIGIN.git/$BAREBITDIR/" 

}

if [ "$USERCOMMAND" = "init" ]; then
	init "$2"
else if [ "$USERCOMMAND" = "add" ]; then
	add "$2"
else if [ "$USERCOMMAND" = "rm" ]; then
	bitrm "$2"
else if [ "$USERCOMMAND" = "clean" ]; then
	clean
else if [ "$USERCOMMAND" = "pull" ]; then
	pull
else if [ "$USERCOMMAND" = "push" ]; then
	push
fi
fi
fi
fi
fi
fi
